# see http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2019

environment:
  EnableNuGetPackageRestore: true
  VCTargetsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\

platform:
- x86
configuration:
- Debug

install:
  - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"

assembly_info:
 patch: true
 file: '**\AssemblyInfo.*'
 assembly_version: '{version}'
 assembly_file_version: '{version}'

dotnet_csproj:
 patch: true
 file: '**\*.csproj'
 package_version: '{version}'

#---------------------------------#
#      build configuration        #
#---------------------------------#
before_build:
- nuget restore

build:
 project: libmspack4n.sln

after_build:
 - 7z a libmspack4n-%appveyor_build_version%.zip libmspack4n\bin\Debug\*

artifacts:
- path: '**\*.nupkg'
- path: '*.zip'

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'Appveyor deployed v$(APPVEYOR_BUILD_VERSION)'
    auth_token:
      secure: Ocl+kToBlL/IWT9+682+RyT3guxvjf/ZROODM+yt9BIAQaRu3xuKTATThJe9+Vuw # from https://github.com/settings/tokens; encrypted at https://ci.appveyor.com/tools/encrypt
    artifact: /(.*\.nupkg)|(.*\.zip)/ # upload NuGet & zip files to release assets
    draft: false
    prerelease: false
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"
  
  - provider: NuGet # See https://www.appveyor.com/docs/deployment/nuget/
    api_key:
      secure: 9elIHDxuSEIvn/us9M5SmtAatYvwZO++m8dYABofIt+/2xcLpuz1Qv9DkypOzpeU # from https://www.nuget.org/account/apikeys; encrypted at https://ci.appveyor.com/tools/encrypt
    artifact: /.*\.nupkg/
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"