//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("libmspack4n")]
[assembly: System.Reflection.AssemblyDescription("A .NET version of the libmspack libmspack library that enables programatically re" +
    "ading and extracting the content of Microsoft cab files.")]
[assembly: System.Reflection.AssemblyCompany("Scott Willeke")]
[assembly: System.Reflection.AssemblyVersion("0.7.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.7.0.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Scott Willeke ©2013-2016")]


